model:
  name: "BasicRNNNetwork"
  parameters:
    state_size: ???  # Example size, will be dynamically set based on environment
    action_size: ???  # Example size, will be dynamically set based on environment
    hidden_size: 128

env:
  name: "CartPole-v1"

optimizer:
  name: "Adam"
  parameters:
    lr: 1e-4

logger:
  name: "Logger"

algorithm:
  name: "REINFORCE"
  parameters:
    gamma: 0.99
    num_episodes: 1000